# OpenAI API設定
# ローカル開発時は.envファイルを使用します
# Streamlit Cloudでデプロイする際は、管理画面の「Secrets」で以下の設定を行ってください:
# OPENAI_API_KEY = "sk-your-actual-api-key-here"

# 注意: このファイルはローカル開発時には空のままにしておきます
# Streamlit Cloudでのみ実際のAPIキーを設定してください